/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdlib.h>
#include "../Inc/usart.h"
#include "../Inc/gpio.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

volatile uint8_t bp = 0;
volatile uint32_t count = 0;
volatile uint32_t ticks = 0;

void EXTI15_10_IRQHandler(void) {
	bp = 1;
	EXTI->PR |= (1 << 13);
}

/* void TIM2_IRQHandler(void) {
	if((TIM2->SR & (1 << 0))) {
		TIM2->SR &= ~(1 << 0);
		count++;
	}
} */

typedef enum {
	STATE_ON,
	STATE_OFF,
} State;

typedef enum {
	BTN_PRESS,
	UPTIME,
	NILL,
} Event;

static State current_state = STATE_OFF;

Event get_event(void) {
	if(bp) {
		bp = 0;
		return BTN_PRESS;
	}

	if(count == 1) {
		ticks++;
		count = 0;

		if(ticks >= 10) {
			ticks = 0;
			return UPTIME;
		}
	}

	return NILL;

}

void update_state(Event event) {
	//if(event == NILL) return;

	/*if(event == UPTIME) {
		send_str("UPTIME: ");
		itoa(ticks,buffer,10);
		send_str(buffer);

		send_char('\r');
		send_char('\n');

	}*/

	switch(current_state) {
		case STATE_ON:
			if(event == BTN_PRESS) {
				led_off();
				//send_str("Led is off");
				//send_char('\r');
				//send_char('\n');
				current_state = STATE_OFF;
			}

			break;

		case STATE_OFF:
			if(event == BTN_PRESS) {
				led_on();
				//send_str("Led is on");
				//send_char('\r');
				//send_char('\n');
				current_state = STATE_ON;
			}

			break;
	}
}

int main(void)
{
    /* Loop forever */
	//usart_init();
	RCC->AHB1ENR |= (1 << 0);
	GPIOA_INIT();
	GPIOC_INIT();
	//start_tim();
	//led_on();
	while(1) {;
		Event event = get_event();
		update_state(event);
	}
}
